
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Feb 12 21:36:13 COT 2015
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TokenERROR = 11;
  public static final int TokenAves = 4;
  public static final int TokenMamiferos = 3;
  public static final int EOF = 0;
  public static final int TokenResultado = 10;
  public static final int TokenMarinos = 8;
  public static final int TokenSalvajes = 6;
  public static final int error = 1;
  public static final int TokenReptiles = 7;
  public static final int TokenDomesticos = 2;
  public static final int TokenRoedores = 5;
  public static final int TokenOperador = 9;
}

